/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 54
#define YY_END_OF_BUFFER 55
static yyconst short int yy_accept[250] =
    {   0,
        0,    0,   55,   54,   52,   53,   32,   30,   28,   29,
       31,   25,   26,   49,   48,   50,   54,   51,   19,   19,
       19,   19,   54,   22,   34,   54,   54,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   54,   54,   54,
        8,   33,    9,   21,    0,   22,    1,    5,    0,   27,
        0,    0,    0,    0,   21,   17,   19,   21,    0,    0,
        0,    0,   16,   23,   44,    0,    0,    7,    0,    0,
        0,    0,    0,   39,    0,    0,    0,   45,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   19,    0,   19,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       37,    0,    0,    0,    0,    0,   38,   10,    0,    0,
        0,    0,    0,   19,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    7,    0,
        0,   13,    0,   42,   47,    0,    0,   40,    0,    3,
        0,   24,   12,    0,   41,    0,   18,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   20,   19,    0,   19,
        0,    0,    0,    4,   15,    0,    0,    0,    0,    0,
       35,    0,   36,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   46,   43,    0,

        0,   14,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   19,    0,    0,   11,    2,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   20,
        0,    6,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    6,    7,    8,    9,    1,   10,
       11,   12,   13,    1,   14,   15,   16,   17,   18,   19,
       20,   21,   21,   22,   23,   24,   25,   26,   27,    1,
       28,    1,    1,   29,   30,   31,   32,   33,   34,   35,
       36,   37,   38,   31,   31,   39,   31,   40,   41,   42,
       31,   43,   44,   45,   46,   47,   48,   49,   50,   31,
       51,    1,   52,    1,   53,    1,   54,   55,   56,   55,

       57,   58,   59,   60,   61,   55,   55,   62,   63,   64,
       65,   66,   55,   67,   55,   64,   55,   55,   68,   55,
       55,   55,   69,   70,   71,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[72] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    1,    2,    1,    1,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        1,    1,    1,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    1,    1,
        1
    } ;

static yyconst short int yy_base[259] =
    {   0,
        0,    0,  848,  820,  819,   69,  818,   67,   71,  817,
      816,   72,  815,  814,   83,   66,   94,   62,   63,   95,
      106,  117,   55,   84,  813,  128,  139,   54,  801,  129,
      132,  797,  794,  802,  128,  805,  791,  161,   65,  116,
      806,  805,  804,  849,  172,  849,  849,  849,  186,  849,
      183,  192,  803,  201,  849,  849,  812,  212,  801,  221,
      232,  800,  849,  849,  849,  188,  799,  849,  798,  127,
      166,  220,  229,  797,  150,  230,  231,  796,  234,  235,
      239,  168,  240,  243,  241,  244,  234,  757,  760,  261,
      289,  304,  319,  334,  345,  793,  354,  363,  792,  372,

      381,  390,  396,  788,  774,  772,  780,  780,  760,  780,
      777,  775,  756,  755,  242,  738,  731,  849,  701,  718,
      370,  685,  681,  849,  715,  425,  436,  703,  447,  458,
      675,  674,  467,  673,  672,  476,  485,  671,  849,  651,
      627,  849,  631,  849,  849,  637,  628,  849,  627,  849,
      628,  849,  849,  621,  849,  626,  849,  592,  557,  498,
      502,  513,  522,  531,  537,  543,  552,  561,  501,  570,
      579,  500,  588,  849,  849,  491,  480,  480,  469,  476,
      849,  457,  849,  483,  599,  445,  444,  608,  617,  624,
      435,  434,  632,  433,  424,  413,  411,  849,  849,  393,

      391,  849,  371,  647,  406,  662,  671,  405,  418,  414,
      686,  695,  397,  704,  849,  849,  298,  323,  715,  322,
      321,  320,  319,  308,  307,  306,  275,  730,  304,  849,
      739,  849,  293,  292,  291,  750,  290,  289,  761,  277,
      275,  772,  272,  271,  783,  270,  269,  266,  849,  287,
      286,  285,  275,  272,  271,  226,  195,   77
    } ;

static yyconst short int yy_def[259] =
    {   0,
      249,    1,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  250,  250,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,

      249,  249,  251,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  252,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,

      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  253,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      254,  249,  249,  249,  249,  255,  249,  249,  256,  249,
      249,  257,  249,  249,  258,  249,  249,  249,    0,  249,
      249,  249,  249,  249,  249,  249,  249,  249
    } ;

static yyconst short int yy_nxt[921] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   20,   21,
       22,   22,   22,   22,   22,   23,   24,    4,   25,   26,
       27,   28,   29,   30,   27,   27,   27,   31,   32,   27,
       27,   33,   34,   35,   27,   27,   36,   37,   27,   27,
       38,    4,    4,    5,    4,    5,    5,    4,    4,    4,
        5,    4,    5,    5,    5,   39,    5,   40,   41,   42,
       43,   45,   47,   48,   49,   54,   50,   56,  247,   57,
       63,   44,   64,   45,   51,   52,   65,   66,   44,   58,
       71,   44,   44,   44,   72,   46,   45,   44,   44,   53,

       53,   53,   53,   53,   53,   53,   53,   53,   45,   44,
       44,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       55,   58,   60,   60,   61,   62,   62,   62,   62,   62,
       62,   88,   58,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   44,   58,   67,   67,   67,   67,   67,   67,
       67,   67,   67,  103,   68,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   74,   68,   78,   75,   76,  104,
       70,   79,   83,   84,   45,   89,  103,   77,   87,   87,
       87,   87,   87,   87,   87,   87,   45,   44,   48,   49,
       65,   66,  103,  108,  103,  105,  244,  115,   46,   90,

       91,   91,   92,   93,   93,   93,   93,   93,   90,   91,
       91,   94,   93,   93,   93,   93,   93,   96,   96,   96,
       96,   96,   96,   96,   96,   96,   97,  241,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   99,   99,   99,
       99,   99,   99,   99,   99,   99,  103,  100,  101,  101,
      101,  101,  101,  101,  102,  103,  103,  103,  100,  106,
      103,  103,  109,  107,  110,  103,  103,  103,  111,  103,
      103,  124,  238,  235,  152,  113,  226,   90,  112,  114,
      153,  119,  116,  118,  117,  120,  197,  140,   69,  121,
      121,  121,  139,  121,  121,  248,  248,  245,  245,  124,

      121,  242,  121,  242,  121,  125,  125,  125,  125,  125,
      125,  125,  125,  125,  124,  239,  239,  236,  236,  209,
      126,  126,  127,  128,  128,  128,  128,  128,  128,  124,
      209,  232,  231,  231,  124,  128,  128,  128,  128,  128,
      128,  128,  128,  128,  124,  230,  124,  209,  209,  228,
      126,  126,  129,  128,  128,  128,  128,  128,  128,   97,
      227,   53,   53,   53,   53,   53,   53,   53,   53,   53,
      131,  131,  131,  131,  131,  131,  131,  131,  131,  132,
      132,  132,  132,  132,  132,  132,  132,  132,  134,  134,
      134,  134,  134,  134,  134,  134,  134,  135,  135,  135,

      135,  135,  135,  135,  135,  135,  136,  136,  136,  136,
      136,  137,  138,  138,  138,  138,  138,  138,  138,  138,
      138,  120,  139,  124,  222,  121,  121,  121,  124,  121,
      121,  209,  219,  217,  216,  215,  121,  214,  121,  214,
      121,  161,  161,  161,  161,  161,  161,  161,  161,  161,
      124,  162,  163,  163,  163,  163,  163,  163,  164,  124,
      212,  211,  162,  163,  163,  163,  163,  163,  163,  165,
      207,  206,  166,  162,   96,   96,   96,   96,   96,   96,
       96,   96,   96,  169,  169,  169,  169,  169,  169,  169,
      169,  169,  172,  172,  172,  172,  172,  172,  172,  172,

      172,  124,  124,  124,  124,  124,  124,  124,  124,  204,
      203,  202,  201,  200,  184,  184,  184,  184,  184,  184,
      184,  184,  184,  124,  199,  198,  124,  193,  185,  186,
      186,  186,  186,  186,  186,  186,  186,  186,  187,  187,
      187,  187,  187,  187,  187,  187,  187,  188,  188,  188,
      188,  188,  189,  188,  188,  188,  188,  188,  190,  191,
      191,  191,  191,  191,  191,  191,  191,  191,  131,  131,
      131,  131,  131,  131,  131,  131,  131,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  195,  195,  195,  195,  195,

      195,  195,  195,  195,  196,  196,  196,  196,  196,  196,
      196,  196,  196,  183,  139,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  208,  208,  208,  208,  208,  208,
      208,  208,  208,  209,  209,  209,  209,  209,  209,  209,
      209,  209,  209,  209,  209,  209,  209,  210,  213,  213,
      213,  213,  213,  213,  213,  213,  213,  124,  182,  181,
      180,  179,  178,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  124,  177,  176,  175,  174,  173,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  221,  221,  221,
      221,  221,  221,  221,  221,  221,  223,  173,  171,  170,

      168,  167,  191,  191,  191,  191,  191,  191,  191,  191,
      191,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      225,  225,  225,  225,  225,  225,  225,  225,  225,  162,
      139,  229,  229,  229,  229,  229,  229,  229,  229,  229,
      124,  160,  159,  158,  157,  156,  233,  233,  233,  233,
      233,  233,  233,  233,  233,  234,  234,  234,  234,  234,
      234,  234,  234,  234,  155,  139,  237,  237,  237,  237,
      237,  237,  237,  237,  237,  154,  139,  240,  240,  240,
      240,  240,  240,  240,  240,  240,  151,  139,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  150,  139,  246,

      246,  246,  246,  246,  246,  246,  246,  246,  149,  139,
      148,  147,  146,  145,  144,  143,  142,  141,  133,  130,
      123,  122,  103,  103,  103,  103,  100,   98,   57,   95,
       44,   44,   44,   86,   85,   82,   81,   80,   73,   44,
       44,   44,   44,   44,   44,   44,   44,  249,    3,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,

      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249
    } ;

static yyconst short int yy_chk[921] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    6,    8,    9,    9,   16,   12,   18,  258,   19,
       23,   23,   23,    6,   12,   12,   24,   24,   18,   19,
       28,   39,   16,    8,   28,    6,   17,    9,   12,   15,

       15,   15,   15,   15,   15,   15,   15,   15,   17,   15,
       24,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       17,   20,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   39,   21,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   40,   22,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   70,   26,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   30,   27,   31,   30,   30,   70,
       26,   31,   35,   35,   45,   40,   75,   30,   38,   38,
       38,   38,   38,   38,   38,   38,   45,   38,   49,   49,
       66,   66,   71,   75,   82,   71,  257,   82,   45,   51,

       51,   51,   51,   51,   51,   51,   51,   51,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   58,  256,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   72,   60,   61,   61,
       61,   61,   61,   61,   61,   73,   76,   77,   61,   72,
       79,   80,   76,   73,   77,   81,   83,   85,   79,   84,
       86,   90,  255,  254,  115,   80,  253,   90,   79,   81,
      115,   86,   83,   85,   84,   87,  252,  251,  250,   87,
       87,   87,  248,   87,   87,  247,  246,  244,  243,   91,

       87,  241,   87,  240,   87,   91,   91,   91,   91,   91,
       91,   91,   91,   91,   92,  238,  237,  235,  234,  233,
       92,   92,   92,   92,   92,   92,   92,   92,   92,   93,
      229,  227,  226,  225,  224,   93,   93,   93,   93,   93,
       93,   93,   93,   93,   94,  223,  222,  221,  220,  218,
       94,   94,   94,   94,   94,   94,   94,   94,   94,   95,
      217,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       97,   97,   97,   97,   97,   97,   97,   97,   97,   98,
       98,   98,   98,   98,   98,   98,   98,   98,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  101,  101,  101,

      101,  101,  101,  101,  101,  101,  102,  102,  102,  102,
      102,  102,  103,  103,  103,  103,  103,  103,  103,  103,
      103,  121,  103,  213,  210,  121,  121,  121,  209,  121,
      121,  208,  205,  203,  201,  200,  121,  197,  121,  196,
      121,  126,  126,  126,  126,  126,  126,  126,  126,  126,
      195,  126,  127,  127,  127,  127,  127,  127,  127,  194,
      192,  191,  127,  129,  129,  129,  129,  129,  129,  129,
      187,  186,  130,  129,  130,  130,  130,  130,  130,  130,
      130,  130,  130,  133,  133,  133,  133,  133,  133,  133,
      133,  133,  136,  136,  136,  136,  136,  136,  136,  136,

      136,  137,  137,  137,  137,  137,  137,  137,  160,  184,
      182,  180,  179,  178,  160,  160,  160,  160,  160,  160,
      160,  160,  160,  162,  177,  176,  172,  169,  161,  162,
      162,  162,  162,  162,  162,  162,  162,  162,  163,  163,
      163,  163,  163,  163,  163,  163,  163,  164,  164,  164,
      164,  164,  164,  165,  165,  165,  165,  165,  165,  166,
      166,  166,  166,  166,  166,  166,  166,  166,  167,  167,
      167,  167,  167,  167,  167,  167,  167,  168,  168,  168,
      168,  168,  168,  168,  168,  168,  170,  170,  170,  170,
      170,  170,  170,  170,  170,  171,  171,  171,  171,  171,

      171,  171,  171,  171,  173,  173,  173,  173,  173,  173,
      173,  173,  173,  159,  173,  185,  185,  185,  185,  185,
      185,  185,  185,  185,  188,  188,  188,  188,  188,  188,
      188,  188,  188,  189,  189,  189,  189,  189,  189,  189,
      190,  190,  190,  190,  190,  190,  190,  190,  193,  193,
      193,  193,  193,  193,  193,  193,  193,  204,  158,  156,
      154,  151,  149,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  206,  147,  146,  143,  141,  140,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  207,  207,  207,
      207,  207,  207,  207,  207,  207,  211,  138,  135,  134,

      132,  131,  211,  211,  211,  211,  211,  211,  211,  211,
      211,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      214,  214,  214,  214,  214,  214,  214,  214,  214,  128,
      214,  219,  219,  219,  219,  219,  219,  219,  219,  219,
      228,  125,  123,  122,  120,  119,  228,  228,  228,  228,
      228,  228,  228,  228,  228,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  117,  231,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  116,  236,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  114,  239,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  113,  242,  245,

      245,  245,  245,  245,  245,  245,  245,  245,  112,  245,
      111,  110,  109,  108,  107,  106,  105,  104,   99,   96,
       89,   88,   78,   74,   69,   67,   62,   59,   57,   53,
       43,   42,   41,   37,   36,   34,   33,   32,   29,   25,
       14,   13,   11,   10,    7,    5,    4,    3,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,

      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 ".\\lex.l"
#define INITIAL 0
#line 2 ".\\lex.l"
    #include "syn.tab.h"
    int nb_ligne = 1;
#line 653 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 15 ".\\lex.l"


#line 807 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 250 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 849 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 17 ".\\lex.l"
return mc_import;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 18 ".\\lex.l"
return bib_process;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 19 ".\\lex.l"
return bib_loop;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 20 ".\\lex.l"
return bib_array;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 21 ".\\lex.l"
{nb_ligne++;
               return fin_instruction;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 24 ".\\lex.l"
return mc_programme;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 25 ".\\lex.l"
return idf;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 26 ".\\lex.l"
return accolade_ouvrante;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 27 ".\\lex.l"
return accolade_fermante;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 29 ".\\lex.l"
return mc_var; 
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 30 ".\\lex.l"
return mc_integer;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 31 ".\\lex.l"
return mc_real;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 32 ".\\lex.l"
return mc_char;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 33 ".\\lex.l"
return mc_string;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 34 ".\\lex.l"
return mc_const;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 35 ".\\lex.l"
return quatre_points;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 36 ".\\lex.l"
return separateur_var;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 37 ".\\lex.l"
return taille_tab;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 38 ".\\lex.l"
return entier;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 39 ".\\lex.l"
return real;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 40 ".\\lex.l"
return caractere;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 41 ".\\lex.l"
return str;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 43 ".\\lex.l"
return affectation;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 44 ".\\lex.l"
return mc_read;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 45 ".\\lex.l"
return parenthese_ouvrante;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 46 ".\\lex.l"
return parenthese_fermante;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 47 ".\\lex.l"
return parenthese_ouvrante_guillemet;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 48 ".\\lex.l"
return signe_de_formatage_integer;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 49 ".\\lex.l"
return signe_de_formatage_real;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 50 ".\\lex.l"
return signe_de_formatage_string;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 51 ".\\lex.l"
return signe_de_formatage_char;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 52 ".\\lex.l"
return guillemet;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 53 ".\\lex.l"
return barre_verticale;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 54 ".\\lex.l"
return arobase; 
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 55 ".\\lex.l"
return mc_write;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 56 ".\\lex.l"
return mc_while;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 57 ".\\lex.l"
return mc_inf;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 58 ".\\lex.l"
return mc_sup;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 59 ".\\lex.l"
return mc_eg;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 60 ".\\lex.l"
return mc_infe;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 61 ".\\lex.l"
return mc_supe;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 62 ".\\lex.l"
return mc_diff;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 63 ".\\lex.l"
return mc_execut;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 64 ".\\lex.l"
{nb_ligne++;
               return pvg_fin;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 66 ".\\lex.l"
return mc_if;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 67 ".\\lex.l"
return mc_end_if;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 68 ".\\lex.l"
return mc_else;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 69 ".\\lex.l"
return addition;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 70 ".\\lex.l"
return multiplication;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 71 ".\\lex.l"
return soustraction;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 72 ".\\lex.l"
return division;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 74 ".\\lex.l"

	YY_BREAK
case 53:
YY_RULE_SETUP
#line 75 ".\\lex.l"
nb_ligne++;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 76 ".\\lex.l"
ECHO;
	YY_BREAK
#line 1162 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 250 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 250 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 249);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 76 ".\\lex.l"
